var TWITTER_API_KEY="API KEY FOR TWITTER API";
var TWITTER_API_KEY_SECRET="API KEY SECRET FOR TWITTER API";
var TWTTER_API_BEARER_TOKEN="BEARER TOKEN FOR TWITTER API";

function getTwitter(){
  //return TwitterWebService.getInstance(TWITTER_ID,TWITTER_LOGIN);
  return TwitterWebService.getInstance(TWITTER_API_KEY,TWITTER_API_KEY_SECRET);
}
